Implement POST /eth-signature/token
givepraise/praise pull request #1044
Opened 2023-05-25 04:38 UTC by mohammadranjbarz

related #723

2023-05-25 09:46 UTC, mohammadranjbarz commented
@kristoferlund  I wasn't sure about endpoint address and the controller to put that code, so let me know if you think  it's better to change it

2023-05-29 06:18 UTC, kristoferlund requested changes
Looks good! 

Perhaps name of the endpoint should be `eth-signature/refresh`?

I'd like to see some more tests:
1. Make request with expired token fails
2. Refresh token
3. Make same request as 1, now it works

2023-05-29 09:27 UTC, mohammadranjbarz commented
> Looks good!
> 
> Perhaps name of the endpoint should be `eth-signature/refresh`?
> 
> I'd like to see some more tests:
> 
> 1. Make request with expired token fails
> 2. Refresh token
> 3. Make same request as 1, now it works

Thanks for your feedback, I'll do them

2023-06-07 12:02 UTC, mohammadranjbarz commented
> Looks good!
> 
> Perhaps name of the endpoint should be `eth-signature/refresh`?
> 
> I'd like to see some more tests:
> 
> 1. Make request with expired token fails
> 2. Refresh token
> 3. Make same request as 1, now it works

@kristoferlund 
I made all changes that you wanted and added some more test cases
but I get this error in ci/cd but the error lines doesn't exist in the codes and I can build locally, can you help me on that

https://github.com/givepraise/praise/actions/runs/5199598195/jobs/9377208506

<img width="1057" alt="Screen Shot 1402-03-17 at 15 30 54" src="https://github.com/givepraise/praise/assets/9850545/4389cd07-d3b1-45bb-9ac8-49d0d31cc218">

2023-06-07 12:18 UTC, kristoferlund commented
@mohammadranjbarz I think the user object in `LoginResponseDto` was added recently by @nebs-dev, have you merged  with latest  changes from `main`?

2023-06-07 12:58 UTC, mohammadranjbarz commented
> @mohammadranjbarz I think the user object in `LoginResponseDto` was added recently by @nebs-dev, have you merged with latest changes from `main`?

@kristoferlund  I just merged `main` to my branch and it got fixed, thank you

2023-06-08 09:02 UTC, kristoferlund requested changes
Looks good, only one small fix needed. We should not use 500 response (only when something is broken).

2023-06-08 10:48 UTC, mohammadranjbarz commented on packages/api/src/auth/eth-signature.service.ts
> +    const tokenPayload = this.jwtService.verify(token, {
@kristoferlund  Done

2023-06-08 19:11 UTC, kristoferlund approved these changes
Great, thanks! Merging.

2023-06-08 19:11 UTC, merged