Refresh accessToken when JWT access token has expired
givepraise/praise pull request #1120
Opened 2023-07-24 12:59 UTC by mohammadranjbarz

related #1007

2023-07-24 13:03 UTC, mohammadranjbarz commented on packages/frontend/src/utils/axios.ts
> +    localStorage.setItem(JSON.stringify(recoilPersist), 'recoil-persist');
@kristoferlund 
It seems we just can use `recoil` inside components so I had to manually put/get to local storage

2023-08-04 12:46 UTC, kristoferlund requested changes
Sorry for slow review @mohammadranjbarz! 

I'd like to see two small changes, other than that all good!

Or btw. Have you tried how the user experience is when token expires and gets refreshed? Since the original request fails, the UI is left in an unclear state. Should we force a UI reload to make sure all looks good?

2023-08-04 12:46 UTC, kristoferlund commented on packages/frontend/src/utils/axios.ts
> +    (err?.response?.data?.code === 1092 || err?.response?.data?.code === 1107)
1092 means unauthenticated user trying to access authenticated resource. This should not trigger a refresh.

2023-08-04 12:46 UTC, kristoferlund commented on packages/frontend/src/utils/axios.ts
> +  const recoilPersist = localStorage.getItem('recoil-persist');
Use `getRecoil(ActiveTokenSet)`, see `auth.ts` for example.

2023-08-11 09:00 UTC, kristoferlund commented
@mohammadranjbarz I finished this as I want to get it out to communities soon.

2023-08-11 09:00 UTC, kristoferlund approved these changes

2023-08-11 09:03 UTC, merged

2023-08-13 06:20 UTC, mohammadranjbarz commented
> @mohammadranjbarz I finished this as I want to get it out to communities soon.

Thanks @kristoferlund , sorry I was busy last week , I couldn't spend time on this