add useraccount crud endpoints
givepraise/praise pull request #843
Opened 2023-02-14 07:03 UTC by CarlosQ96

WIP
- Writing tests for the userAccounts endpoints.

2023-02-15 08:12 UTC, CarlosQ96 commented
You can start taking a look Kris! I have a few question I left in the description.
I think this base works, but I think some modifications might be done, as I might have a few confusions after looking at the discord bot.

2023-02-15 08:13 UTC, CarlosQ96 commented
Also the linter threw many errors, on all files, and running the linter locally also does errors everywhere. 
linter --fix does not work.

Any suggestions for linting or how are you handling it?

2023-02-15 11:20 UTC, kristoferlund requested changes
Nice @CarlosQ96 !!

The different ids in play here are: 

`user._id` – MongoDb User Id

`useraccount._id` – MongoDb User Id
`useraccount.accountId` – Platform specific account id, in the case of Discord it is the Discord user snowflake id 

So, for your questions: 

1. Discord in our current case. When adding Slack, that will have another accountId.
2. No, see above.
3. Yes, create a new migration, old ones are not rerun.

I realized we need to be able to GET and PATCH both with `user._id` and `useraccount.accountId`. I don't know how to best structure the endpoints. 

Can we use same endpoints and allow both types of ids? Mongoose provides this easy check: `Types.ObjectId.isValid(id)`

2023-02-15 11:23 UTC, kristoferlund commented
> Also the linter threw many errors, on all files, and running the linter locally also does errors everywhere. linter --fix does not work.
> 
> Any suggestions for linting or how are you handling it?

For linting, I get this: `✖ 37 problems (3 errors, 34 warnings)`. Do you see more? I'll open up a new issue to fix these.

2023-02-15 13:35 UTC, CarlosQ96 commented on packages/api2/src/useraccounts/useraccounts.service.ts
> +      .select('_id user accountId name avatarId platform createdAt updatedAt')
Thanks will do

2023-02-15 13:36 UTC, CarlosQ96 commented
> > Also the linter threw many errors, on all files, and running the linter locally also does errors everywhere. linter --fix does not work.
> > Any suggestions for linting or how are you handling it?
> 
> For linting, I get this: `✖ 37 problems (3 errors, 34 warnings)`. Do you see more? I'll open up a new issue to fix these.

I get 38 problems, I think its the same.

2023-02-15 13:37 UTC, CarlosQ96 commented
Thanks for the feedback will add it today, I knew we had to do changes as I was unsure about a few things. But we can reuse this base to finish it.
Regarding the Ids, I look into making it restful. Or use the same ones, maybe something more elegant.

2023-02-15 15:39 UTC, kristoferlund commented
```
GET /useraccount?id=xxx&accountId=xxx
PATCH /useraccount?id=xxx&accountId=xxx
```

2023-02-23 06:42 UTC, CarlosQ96 commented
Fixed the duck db issue I had, made the changed just missing to fix 1 test. I will push it first thing tomorrow morning. (my morning)

2023-03-02 08:20 UTC, merged